.

diff --git a/Ejemplo_ASP.NET_MVC6/Scripts/Ejemplo_03_CRUD_Simple_Login/docker/Dockerfile.mssql b/Ejemplo_ASP.NET_MVC6/Scripts/Ejemplo_03_CRUD_Simple_Login/docker/Dockerfile.mssql
--- a/Ejemplo_ASP.NET_MVC6/Scripts/Ejemplo_03_CRUD_Simple_Login/docker/Dockerfile.mssql
+++ b/Ejemplo_ASP.NET_MVC6/Scripts/Ejemplo_03_CRUD_Simple_Login/docker/Dockerfile.mssql
@@ -5,6 +5,7 @@ FROM mcr.microsoft.com/mssql/server:2022-latest
 ENV ACCEPT_EULA=Y
 ENV MSSQL_SA_PASSWORD=MSS-fernando-123
 
+
 # herramientas para mss
 USER root
 RUN apt-get update && \
@@ -17,11 +18,22 @@ RUN echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod foca
 RUN apt-get update
 
 # instalando paquetes
-RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 || echo "Failed to install msodbcsql17"
+RUN apt-get install -y unixodbc || echo "Failed to install unixodbc"
+
+RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 || echo "Failed to install msodbcsql17"
 RUN apt-get install -y mssql-tools || echo "Failed to install mssql-tools"
+
 RUN apt-get install -y unixodbc-dev || echo "Failed to install unixodbc-dev"
 
+RUN apt-get install -y nano || echo "Failed to install nano"
+
+#COPY my_sql_server_cert.crt /usr/local/share/ca-certificates/
+
+RUN update-ca-certificates
+
 RUN apt-get clean && rm -rf /var/lib/apt/lists/*
+
+RUN ln -s /opt/mssql-tools18 /opt/mssql-tools
 
 # directorio de trabajo para los scripts
 
