contenedor sql

diff --git a/Ejemplo_ASP.NET_MVC6/Ejemplo_01/Ejemplo_01_0_Docker/Dockerfile.mssql b/Ejemplo_ASP.NET_MVC6/Ejemplo_01/Ejemplo_01_0_Docker/Dockerfile.mssql
--- a/Ejemplo_ASP.NET_MVC6/Ejemplo_01/Ejemplo_01_0_Docker/Dockerfile.mssql
+++ b/Ejemplo_ASP.NET_MVC6/Ejemplo_01/Ejemplo_01_0_Docker/Dockerfile.mssql
@@ -1,3 +1,5 @@
+
+
 # imagen oficial mss 
 FROM mcr.microsoft.com/mssql/server:2022-latest
 
@@ -20,7 +22,7 @@ RUN apt-get update
 # instalando paquetes
 RUN apt-get install -y unixodbc || echo "Failed to install unixodbc"
 
-RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 || echo "Failed to install msodbcsql17"
+RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 || echo "Failed to install msodbcsql18"
 RUN apt-get install -y mssql-tools || echo "Failed to install mssql-tools"
 
 RUN apt-get install -y unixodbc-dev || echo "Failed to install unixodbc-dev"
@@ -35,16 +37,26 @@ RUN apt-get clean && rm -rf /var/lib/apt/lists/*
 
 RUN ln -s /opt/mssql-tools18 /opt/mssql-tools
 
+
+
 # directorio de trabajo para los scripts
 
-ARG PROJECT_PATH=Scripts/Ejemplo_01_CRUD_MVC_Simple/MSSQL
-ARG BUILD_ROOT=/src/sql_script
+ARG EJEMPLO="Ejemplo_01"
+ARG PROJECT_DIR="Ejemplo_01_0_database_MSSQL"
+ARG BASE_PATH="/workspaces/Ejemplos_ASP.NET_MVC6/Ejemplo_ASP.NET_MVC6"
+ARG PROJECT_PATH="${BASE_PATH}/${EJEMPLO}/${PROJECT_DIR}"
+ARG BUILD_ROOT="/src/sql_script"
+ARG SRC_APP=./"${PROJECT_DIR}"
 
-WORKDIR $BUILD_ROOT
 
-COPY ${PROJECT_PATH}/. ${BUILD_ROOT}
+# WORKDIR ${BUILD_ROOT}
+WORKDIR /src/sql_script/
 
-# puerto del servicio
+# copiando el script para crear la base de datos
+# COPY ${PROJECT_PATH}/. ${BUILD_ROOT}
+COPY ${SRC_APP}/. /src/sql_script
+
+# puerto del servicio 
 EXPOSE 1433
 
 # punto de entrada
